This julia notebook uses [Simons' CMAP](https://cmap.readthedocs.io/en/latest/) to depict output of the Darwin model in context of the [CBIOMES](https://cbiomes.org) project.

<img src="../figs/cbiomes-01.png" alt="Drawing" style="height: 50px;"/>

**Pre-requisites:**

- 1) install the [PyCmap python package and its dependencies](https://github.com/simonscmap/pycmap) using `pip`.
- 2) compile [PyCall.jl](https://github.com/simonscmap/pycmap) using external python distribution that installed `PyCmap`.

_Note:_ the commented out `pip install pycmap` call does not need to be repeated every time. However, if the `pyimport` call later returns an error then please try uncommenting the `pip install pycmap` call and start over.

In [1]:
#run(`pip install pycmap`) #pycmap is used via PyCall later

run(pipeline(`which python`,"whichpython.txt")) #external python path
ENV["PYTHON"]=readline("whichpython.txt")
import Pkg; Pkg.add("PyCall"); Pkg.build("PyCall")

  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `~/mywork/projects_major/2019-jlpkgs/Cbiomes2019Notebooks/Project.toml`
 [no changes]
  Updating `~/mywork/projects_major/2019-jlpkgs/Cbiomes2019Notebooks/Manifest.toml`
 [no changes]
  Building Conda ─→ `~/.julia/packages/Conda/kLXeC/deps/build.log`
  Building PyCall → `~/.julia/packages/PyCall/ttONZ/deps/build.log`

**Now we can import `pycmap` inside `julia` using `PyCall.jl`.**

In [2]:
using PyCall
PyCmap = pyimport("pycmap")

┌ Info: Precompiling PyCall [438e738f-606a-5dbb-bf0a-cddfbfd45ab0]
└ @ Base loading.jl:1186

PyObject <module 'pycmap' from '/anaconda3/lib/python3.7/site-packages/pycmap/__init__.py'>

#### Get the cmap data catalog

This will create a `data/` folder should contain `catalog.csv`. Another folder named `embed/` gets created below.

In [2]:
getCatalog = pyimport("opedia.getCatalog")

PyObject <module 'opedia.getCatalog' from '/anaconda3/lib/python3.7/site-packages/opedia/getCatalog.py'>

#### Import opedia functionalities

In [3]:
opediareg = pyimport("opedia.plotRegional")
opediasub = pyimport("opedia.subset")

PyObject <module 'opedia.subset' from '/anaconda3/lib/python3.7/site-packages/opedia/subset.py'>

#### Download a regional Chlorophyll data set from the Darwin model

This will download a file called `data/RM_tblDarwin_Nutrient_3day_FeT_darwin_3day.csv`.

In [4]:
tables = ["tblDarwin_Nutrient_3day"] # see catalog.csv  for the complete list of tables and variable names
variables = ["FeT_darwin_3day"] # see catalog.csv  for the complete list of tables and variable names   
startDate = "1994-01-03"
endDate = "1994-01-03"
lat1, lat2 = 10, 70
lon1, lon2 = -180, -80
depth1, depth2 = 0, 10
fname = "regional"
exportDataFlag = true # false if you you do not want to download data

opediareg.regionalMap(tables, variables, startDate, endDate, lat1, lat2, lon1, lon2, depth1, depth2, fname, exportDataFlag)

#### Load the same data directly as a dataframe

In [5]:
df = opediasub.spaceTime(tables[1], variables[1], startDate, endDate, lat1, lat2, lon1, lon2, depth1, depth2)

PyObject              time    lat     lon  depth  FeT_darwin_3day
0      1994-01-03  10.25 -179.75    5.0     3.598904e-07
1      1994-01-03  10.25 -179.25    5.0     3.588667e-07
2      1994-01-03  10.25 -178.75    5.0     3.541469e-07
3      1994-01-03  10.25 -178.25    5.0     3.503552e-07
4      1994-01-03  10.25 -177.75    5.0     3.484683e-07
5      1994-01-03  10.25 -177.25    5.0     3.482929e-07
6      1994-01-03  10.25 -176.75    5.0     3.482747e-07
7      1994-01-03  10.25 -176.25    5.0     3.526290e-07
8      1994-01-03  10.25 -175.75    5.0     3.706651e-07
9      1994-01-03  10.25 -175.25    5.0     3.837622e-07
10     1994-01-03  10.25 -174.75    5.0     3.901298e-07
11     1994-01-03  10.25 -174.25    5.0     3.886877e-07
12     1994-01-03  10.25 -173.75    5.0     3.882265e-07
13     1994-01-03  10.25 -173.25    5.0     3.939976e-07
14     1994-01-03  10.25 -172.75    5.0     3.988823e-07
15     1994-01-03  10.25 -172.25    5.0     3.981881e-07
16     1994-01-03  10.25 -171.75    5.0     3.931032e-07
17     1994-01-03  10.25 -171.25    5.0     3.894783e-07
18     1994-01-03  10.25 -170.75    5.0     3.909051e-07
19     1994-01-03  10.25 -170.25    5.0     3.948873e-07
20     1994-01-03  10.25 -169.75    5.0     3.988555e-07
21     1994-01-03  10.25 -169.25    5.0     4.064104e-07
22     1994-01-03  10.25 -168.75    5.0     4.181881e-07
23     1994-01-03  10.25 -168.25    5.0     4.248223e-07
24     1994-01-03  10.25 -167.75    5.0     4.414154e-07
25     1994-01-03  10.25 -167.25    5.0     4.438598e-07
26     1994-01-03  10.25 -166.75    5.0     4.168298e-07
27     1994-01-03  10.25 -166.25    5.0     4.085711e-07
28     1994-01-03  10.25 -165.75    5.0     4.094346e-07
29     1994-01-03  10.25 -165.25    5.0     4.266224e-07
...           ...    ...     ...    ...              ...
23970  1994-01-03  69.75  -94.75    5.0              NaN
23971  1994-01-03  69.75  -94.25    5.0              NaN
23972  1994-01-03  69.75  -93.75    5.0              NaN
23973  1994-01-03  69.75  -93.25    5.0              NaN
23974  1994-01-03  69.75  -92.75    5.0              NaN
23975  1994-01-03  69.75  -92.25    5.0     1.052383e-03
23976  1994-01-03  69.75  -91.75    5.0     1.052384e-03
23977  1994-01-03  69.75  -91.25    5.0     1.052182e-03
23978  1994-01-03  69.75  -90.75    5.0     1.051339e-03
23979  1994-01-03  69.75  -90.25    5.0     1.047807e-03
23980  1994-01-03  69.75  -89.75    5.0     1.037787e-03
23981  1994-01-03  69.75  -89.25    5.0     1.020743e-03
23982  1994-01-03  69.75  -88.75    5.0     1.018736e-03
23983  1994-01-03  69.75  -88.25    5.0     1.025022e-03
23984  1994-01-03  69.75  -87.75    5.0     1.028487e-03
23985  1994-01-03  69.75  -87.25    5.0     1.037947e-03
23986  1994-01-03  69.75  -86.75    5.0     1.040293e-03
23987  1994-01-03  69.75  -86.25    5.0     1.040276e-03
23988  1994-01-03  69.75  -85.75    5.0     1.039155e-03
23989  1994-01-03  69.75  -85.25    5.0              NaN
23990  1994-01-03  69.75  -84.75    5.0              NaN
23991  1994-01-03  69.75  -84.25    5.0              NaN
23992  1994-01-03  69.75  -83.75    5.0     1.015779e-03
23993  1994-01-03  69.75  -83.25    5.0     1.008644e-03
23994  1994-01-03  69.75  -82.75    5.0     1.012755e-03
23995  1994-01-03  69.75  -82.25    5.0     1.052385e-03
23996  1994-01-03  69.75  -81.75    5.0     1.052385e-03
23997  1994-01-03  69.75  -81.25    5.0     1.052385e-03
23998  1994-01-03  69.75  -80.75    5.0     1.052409e-03
23999  1994-01-03  69.75  -80.25    5.0     1.052415e-03

[24000 rows x 5 columns]

┌ Warning: `getindex(o::PyObject, s::AbstractString)` is deprecated in favor of dot overloading (`getproperty`) so elements should now be accessed as e.g. `o."s"` instead of `o["s"]`.
│   caller = show(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::MIME{Symbol("text/html")}, ::PyObject) at PyCall.jl:895
└ @ PyCall /Users/gforget/.julia/packages/PyCall/ttONZ/src/PyCall.jl:895